version: '3.5'
networks:
  course-network:
    driver: bridge
services:
  db:
    image: postgres:14
    container_name: pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
      - POSTGRES_HOST=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    networks:
      - course-network

  python:
    build:
      context: ./
    container_name: course
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@pg:5432/test_db
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - course-network