openapi: "3.0.0"
servers:
  - url: 'https://ubademy-14-prod.herokuapp.com/'
info:
  description: Course API encargada de todas las operaciones relacionadas a cursos
  version: 0.2.0
  title: Course

tags:
  - name: Course
    description: Operaciones sobre cursos

paths:
  '/courses/create':
    'post':
      tags:
        - Course
      description: Crea un curso nuevo
      parameters:
        - in: header
          name: x-access-token
          required: true
          description: token recibido del usuario que desea editar el curso
      requestBody:
        description: body para la creacion del curso
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/courseCreate'
      responses:
        '200':
          description: Curso creado correctamente
        '400':
          description: Bad Request

  '/courses':
    'get':
      tags:
        - Course
      description: Obtengo una lista con todos los cursos
      parameters:
        - in: query
          name: location
          example: 'Colombia'
        - in: query
          name: name
          example: 'Algoritmos2'
        - in: query
          name: creator_name
          example: 'Essaya'
        - in: query
          name: hashtags
          example: 'python,nacho,branca'
        - in: query
          name: type
          example: 'Programacion'
        - in: query
          name: subscription
          example: 'Premium'
        - in: query
          name: offset
          example: 0
        - in: query
          name: limit
          example: 500

      responses:
        '200':
          description: Todo okay
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/coursesList'
        '400':
          description: Bad Request

  '/courses/:id/view':
    'get':
      tags:
        - Course
      description: Obtiene informacion mas detallada sobre el curso
      parameters:
        - in: path
          name: id
          description: id del curso
          required: true
        - in: header
          name: x-access-token
          required: true
          description: token recibido de usuario
      requestBody:
        description: Body para obtener la informacion de un curso
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getCourseInfo'
      responses:
        '200':
          description: Todo okay
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/courseInfo'
        '404':
          description: Curso no existe

  '/courses/:id':
    'post':
      tags:
        - Course
      description: Se inscribe un estudiante al curso
      parameters:
        - in: path
          name: id
          description: id del curso
          required: true
        - in: header
          name: x-access-token
          required: true
          description: token recibido del usuario que desea inscribirse al curso
      responses:
        '200':
          description: Usuario suscrito correctamente
        '400':
          description: Bad Request

    'delete':
      tags:
        - Course
      description: Elimina curso existente
      parameters:
        - in: path
          name: id
          description: id del curso
          required: true
        - in: header
          name: x-access-token
          required: true
          description: token recibido de usuario
      requestBody:
        description: Body para eliminar un curso
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deleteCourse'
      responses:
        '200':
          description: Curso eliminado correctamente
        '400':
          description: Invalid user action
        '401':
          description: Token invalido
        '403':
          description: No token provisto
        '404':
          description: Curso no encontrado

    'patch':
      tags:
        - Course
      description: Modifica la informacion de un curso
      parameters:
        - in: path
          name: id
          description: id del curso
          required: true
        - in: header
          name: x-access-token
          required: true
          description: token recibido del usuario que desea editar el curso
      requestBody:
        description: Body para la edicion del curso
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/editCourse'
      responses:
        '200':
          description: Curso editado correctamente
        '400':
          description: Invalid info
        '401':
          description: Invalid user action
        '403':
          description: No token provisto
        '404':
          description: Course does not exist
        '405':
          description: El usuario no es el creador del curso

  '/courses/collaborators':
    'post':
      tags:
        - Course
      description: Agrega un colaborador al curso
      parameters:
        - in: header
          name: x-access-token
          required: true
          description: token recibido del creador del curso
      requestBody:
        description: Body para agregar un colaborador
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/courseAddCollaborator'
      responses:
        '200':
          description: Collaborator agregado correctamente
        '401':
          description: Token invalido
        '403':
          description: No token provisto
        '404':
          description: El collaborator no existe

    'delete':
      tags:
        - Course
      description: Quita a un colaborador del curso
      parameters:
        - in: header
          name: x-access-token
          required: true
          description: token recibido del creador del curso
      requestBody:
        description: Body para quitar un colaborador
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/courseRemoveCollaborator'
      responses:
        '200':
          description: Collaborator removido correctamente
        '401':
          description: Token invalido
        '403':
          description: No token provisto
        '404':
          description: El collaborator no existe

components:
  schemas:
    courseCreate:
      type: object
      required:
        - name
        - description
        - hashtags
        - type
        - amount_exams
        - subscription
        - location
      properties:
        name:
          type: string
          example: 'Mas Python que nunca'
        description:
          type: string
          example: 'Van a codear muchas cosas en python y van a ver que es alto lenguaje'
        hashtags:
          type: string
          example: '#Python, #Sarasa'
        type:
          type: string
          example: 'Programacion'
        exams:
          type: integer
          example: 3
        subscription:
          type: string
          example: 'Premium'
        location:
          type: string
          example: 'Obera'

    coursesList:
      type: object
      properties:
        name:
          type: string
          example: 'Mas Python que nunca'
        id:
          type: integer
          example: 1
        creator_name:
          type: string
          example: 'Essaya'
        subscription:
          type: string
          example: 'Premium'
        location:
          type: string
          example: 'Obera'
        hashtags:
          type: string
          example: '#FIUBA'
        desciption:
          type: string
          example: 'descripcion del curso'
        exams:
          type: integer
          example: 1
        type:
          type: string
          example: 'Programacion'


    editCourse:
      type: object
      properties:
        name:
          type: string
          example: 'El regreso de Python'
        description:
          type: string
          example: 'Van a codear muchas cosas en python y van a ver que es alto lenguaje'
        hashtags:
          type: string
          example: '#Python, #Sarasa, #Fulano'
        location:
          type: string
          example: 'Corrientes'

    deleteCourse:
      type: object
      properties:
        course_id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 1

    courseInfo:
      properties:
        name:
          type: string
          example: 'Mas Python que nunca'
        creator_name:
          type: string
          example: 'Essaya'
        description:
          type: string
          example: 'Van a codear muchas cosas en python y van a ver que es alto lenguaje'
        hashtags:
          type: string
          example: 'Python, Sarasa'
        type:
          type: string
          example: 'Programacion'
        exams:
          type: integer
          example: 3
        subscription:
          type: string
          example: 'Premium'
        location:
          type: string
          example: 'Obera'
        canEdit:
          type: boolean
          example: true

    courseAddCollaborator:
      type: object
      required:
        - id
        - collaborator_id
      properties:
        id:
          type: integer
          example: 10
        collaborator_id:
          type: integer
          example: 50

    courseRemoveCollaborator:
      type: object
      required:
        - id_creator
        - id_course
        - collaborator_mail
      properties:
        id:
          type: integer
          example: 1
        user_to_remove:
          type: integer
          example: 50

    getCourseInfo:
      type: object
      required:
        -id
      properties:
        id:
          type: integer
          example: 1
